### ISSUE TITLE
This downloads only unsplash.it images and not unsplash.com

### ISSUE THREAD

**Issue by CodeBrauer** [MehediH/Bulksplash#1]
Unsplash.it has "only" [1084 files](https://unsplash.it/images)
Unsplash.com has more than [184.000 photos](https://unsplash.com/developers)

You can register to the official unsplash API however [there is a limit](https://unsplash.com/documentation#rate-limiting)

**Comment by MehediH** [comment]
500 request per hour is a bit too limited, don't you think?

**Comment by grobmeier** [comment]
Each user should have an api key him/herself. 500 requests could be 500 downloads in an hour, I don't find this limiting for a normal use case. +1 on unsplash.com

**Comment by MehediH** [comment]
@grobmeier Pretty sure that's not possible? Can you link me to the relevant documentation?

**Comment by CodeBrauer** [comment]
Assumed unsplash.com will approve every API key request for production - this could work with some changes.

However this project currently won't be possible with the [API terms](https://medium.com/unsplash-unfiltered/unsplash-api-our-terms-explained-c95f84894360)

> 1.) You cannot use the Unsplash name directly in your application name.
> 4.) If using the production-level rate-limiting, you must credit the photographers with a link back to their Unsplash profile.
> 5.) Do not abuse the APIs. Too many requests too quickly will get your access turned off.

I don't know if a frontend scraper would be blocked also and how it fits to this terms<br>(because frontend != API terms?)

**Comment by MehediH** [comment]
To be honest guys 1000 files is more than enough for most people who will use this (aka designers looking for stock images for their design work).

**Comment by grobmeier** [comment]
@MehediH if you don't want to support the original Unsplash, you should consider make that more clear in your README. So far my assumption was this tool would help me with my daily operations with Unsplash, not with a limited subset of it not to speak with something which is just called Unsplash, but is not the original. To me, Unsplash.it and Unsplash got two total different goals. Downloading in Bulk from Unsplash.it does not make any sense

**Comment by MehediH** [comment]
I've just fixed the issue, and you can try it out right now with the latest update. I'm still waiting for Unsplash to approve the production API key though, which will take a week or so to happen.
