### ISSUE TITLE
Is your client ID supposed to be in the code?

### ISSUE THREAD

**Issue by SohamG** [MehediH/Bulksplash#13]
https://github.com/MehediH/Bulksplash/blob/3a34a6d7e7c321952c4b9b3ba51c62b591b85977/index.js#L61

**Comment by MehediH** [comment]
Yes. The software is meant to be a quick download-and-use kind of thing, ready out of the box. Getting API access will be a long process for the user.

**Comment by SohamG** [comment]
Oh, just wanted to be sure
