### ISSUE TITLE
How do I install / use this?

### ISSUE THREAD

**Issue by esomola** [MehediH/Bulksplash#19]
I am a newbie, how do I install or use this?

**Comment by andreaselia** [comment]
- Clone the repository
- `cd` into the repository folder
- Run `node .`
- Follow the steps
- Done 😄

**Comment by XiaCongcong** [comment]
https://www.ilovefreesoftware.com/04/windows/image-photo/unsplash-bulk-download.html
@esomola

**Comment by MehediH** [comment]
Hey, please check the updated readme for better instructions on how to use this.
