### ISSUE TITLE
Not downloading via Collection URl

### ISSUE THREAD

**Issue by bharatxxx007** [MehediH/Bulksplash#31]
Hello,

When I am adding a collection URL lets say for a niche of Luxury.

https://unsplash.com/s/collections/luxury

It's says the URL is invalid.

Do kindly let know if there is another format to enter a URL for collection.

Thanks

**Comment by darioajr** [comment]
Need a more specific url, with the collection ID
example:
https://unsplash.com/collections/2574763/luxury
