### ISSUE TITLE
Where can I add my personal API key?

### ISSUE THREAD

**Issue by rotaugenlaubfrosch** [MehediH/Bulksplash#43]
Thank you for this great script! 
Bulksplash didn't ask me about my API key. Is there an option where I can submit my own API key? It would be great if there was a separate option for that (e.g. "--key" or something like that).
Thank you

**Comment by stephanedebove** [comment]
same problem here. API key is not asked, and what is the option to add it in the command line?

As a result no image is dowloaded ECONNREFUSED.

**Comment by MehediH** [comment]
just pushed a new update to npm
