### ISSUE TITLE
Only 30 pictures download

### ISSUE THREAD

**Issue by alexvaa** [MehediH/Bulksplash#5]
after command  node index --amount=1000
only 30 pictures download

node index --amount=1000

Welcome to Bulksplash! (Powered by Unsplash.com)

Downloading 1000 random images :)

Downloading images from:

Brxxto (https://unsplash.com/@brxxto)
Paul Jarvis (https://unsplash.com/@pjrvs)
Matt Aunger (https://unsplash.com/@mattaunger)
Julian Klumpers (https://unsplash.com/@julianklumpers)
reza shayestehpour (https://unsplash.com/@r_shayesrehpour)
Neven Krcmarek (https://unsplash.com/@nevenkrcmarek)
Vladimir Kudinov (https://unsplash.com/@madbyte)
Chris Benson (https://unsplash.com/@maui354)
Richard Clark (https://unsplash.com/@digimist)
Kaitlyn Jameson (https://unsplash.com/@willsk)
Zoltan Kovacs (https://unsplash.com/@kovacsz1)
Theodora  Lee (https://unsplash.com/@theodoraaaa)
kazuend (https://unsplash.com/@kazuend)
Gabriel Santiago (https://unsplash.com/@gabrielssantiago)
Ahmet Yalçınkaya (https://unsplash.com/@ahmetyalcinkaya)
Todd Quackenbush (https://unsplash.com/@toddquackenbush)
Christoffer Engström (https://unsplash.com/@christoffere)
wu yi (https://unsplash.com/@takeshi2)
Jonathan M. Hethey (https://unsplash.com/@jonathanmh)
Tanaphong Toochinda (https://unsplash.com/@daen_2chinda)
Chris Benson (https://unsplash.com/@maui354)
Christian Löhner (https://unsplash.com/@diren89)
Daryn  Bartlett (https://unsplash.com/@darynmae)
anne-marie robert (https://unsplash.com/@annemarierobert)
Kevin Rajaram (https://unsplash.com/@kevinrajaram)
Jack Gisel (https://unsplash.com/@jackgisel)
Ashim D’Silva (https://unsplash.com/@randomlies)
ludwig friborg (https://unsplash.com/@ludwig_friborg)
Jez Timms (https://unsplash.com/@jeztimms)
Allef Vinicius (https://unsplash.com/@seteales)
====---------------------------------------------------------------------------------------------------------------------------------------------

then exit with out error

service is disable some time, need to process request code != 200

**Comment by teekey-dev** [comment]
Same here, it downloads only up to 30 pics.

**Comment by jaweesner** [comment]
The unspash api limits the amount of elements retrieved to 30 per page, and the code doesn't consider pagination.

**Comment by nair-sreerag** [comment]
I have fixed this issue and created a pull request. Please clone my fork and verify.

**Comment by MehediH** [comment]
This should be fixed in the latest update!
